global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  routes:
  - match:
      alertname: HighCPUUsage
  receiver: 'executor'
receivers:
- name: 'executor'
  webhook_configs:
  - url: 'http://172.232.66.49:9099/receive'
    send_resolved: false
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
